### ISSUE TITLE
貌似现在出问题了？

### ISSUE THREAD

**Issue by Aruelius** [nladuo/tieba_autosign#3]
正在模拟登陆百度贴吧....
Traceback (most recent call last):
  File "get_cookies.py", line 20, in <module>
    app_continue_span = driver.find_element_by_id('index-app-continue')
  File "/usr/lib/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 330, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/lib/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 832, in find_element
    'value': value})['value']
  File "/usr/lib/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: {"errorMessage":"Unable to find element with id 'index-app-continue'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"99","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:38299","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"id\", \"sessionId\": \"67cca250-8b78-11e7-a98d-ff7b3de4df8c\", \"value\": \"index-app-continue\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/67cca250-8b78-11e7-a98d-ff7b3de4df8c/element"}}
Screenshot: available via screen

正在退出

试过五台服务器+一台mac+一台本地ubuntu，都这样= =！而且不兼容python3

**Comment by nladuo** [comment]
刚刚试了一下，有个页面变化了，所以之前的代码报异常了。目前还不支持部署在服务器上，部署在服务器上要输入手机号验证比较麻烦。

**Comment by Aruelius** [comment]
感谢更新~

**Comment by Aruelius** [comment]
话说get_cookies.py好像没更新

**Comment by Aruelius** [comment]
正在模拟登陆百度贴吧....
遇到验证码, 请查看vcode.png, 然后填写验证码: nyyw
您输入的验证码为:" nyyw "
登陆成功, 开始签到!
Traceback (most recent call last):
  File "sign.py", line 84, in <module>
    expand_more = driver.find_element_by_xpath("//div[@class='expand-all']/p")
  File "/usr/lib/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 832, in find_element
    'value': value})['value']
  File "/usr/lib/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: {"errorMessage":"Unable to find element with xpath '//div[@class='expand-all']/p'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"112","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:49118","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"xpath\", \"sessionId\": \"334f7d90-8bd2-11e7-84d2-d3aadf2b7351\", \"value\": \"//div[@class='expand-all']/p\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/334f7d90-8bd2-11e7-84d2-d3aadf2b7351/element"}}
Screenshot: available via screen

正在退出

**Comment by nladuo** [comment]
get_cookies的先不要看了，那个主要是打算写给服务器用的。当时想的是，登陆一次之后，百度可能就记录服务器的ip，然后就没有验证码了。不过手机号验证的还没搞定，所以暂时也就没用。

**Comment by Aruelius** [comment]
嗯，不过sign.py也不能用。。。报错就是上面的

**Comment by nladuo** [comment]
是我关注的贴吧太多了，所以有expand-all这个标签（要点一下才能显示出所有关注的贴吧）。刚刚加了个try catch你可以再试试。（这个项目是当时学习一下selenium然后自己用的，没顾虑那么多）

**Comment by Aruelius** [comment]
[root@host tieba_autosign]# python3 sign.py 
正在模拟登陆百度贴吧....
Traceback (most recent call last):
  File "sign.py", line 45, in <module>
    driver = webdriver.PhantomJS(executable_path=exe_path, desired_capabilities=dcap)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error``

**Comment by nladuo** [comment]
py2也不行？

**Comment by nladuo** [comment]
你是不是phantomjs或者selenium的安装有问题呢？我看到第一行就报错了。
``` sh
driver = webdriver.PhantomJS(executable_path=exe_path, desired_capabilities=dcap)
```

**Comment by Aruelius** [comment]
[root@miku tieba_autosign]# python2.7 sign.py 
正在模拟登陆百度贴吧....
遇到验证码, 请查看vcode.png, 然后填写验证码: luk^Hmk
您输入的验证码为:" lumk "
登陆成功, 开始签到!
全部签到完成!!!
正在退出
[root@miku tieba_autosign]# 
用python2.7就好了诶

**Comment by nladuo** [comment]
我本地测的话python3也没这个问题，感觉是selenium出问题的。

**Comment by Aruelius** [comment]
我刚刚是新开了一台服务器来测试的，那估计就是selenium的问题了。

**Comment by nladuo** [comment]
恩。先close了。
